const DB_NAME='mama-zukan-db', DB_VERSION=2;
const charSections=[['overview','概要'],['appearance','外見'],['personality','性格'],['speech','口調・呼称'],['relationship','関係性'],['intimacy','親密時'],['imageRules','画像生成ルール'],['notes','重要メモ']];
const commonSections=[['world','世界・世代'],['sharedRules','共通運用'],['imageRules','画像生成ルール'],['intimacyRules','親密シーン共通'],['informationBoundaries','情報共有・人格境界'],['recoveryNotes','復元・優先順位']];
const personaSections=[['identity','人格の核'],['voice','一人称・呼称・口調'],['role','役割'],['interaction','会話・対応方針'],['sharing','情報共有'],['settingsManagement','設定管理'],['fullSpec','完全版設定'],['notes','重要メモ']];
let db, chars=[], personas=[], common=null, mode='characters', currentChar=null, currentPersona=null, charSection='overview', commonSection='world', personaSection='identity', dirty={characters:false,common:false,personas:false};

function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VERSION);r.onupgradeneeded=e=>{const d=e.target.result;if(!d.objectStoreNames.contains('characters'))d.createObjectStore('characters',{keyPath:'id'});if(!d.objectStoreNames.contains('commonSettings'))d.createObjectStore('commonSettings',{keyPath:'id'});if(!d.objectStoreNames.contains('personas'))d.createObjectStore('personas',{keyPath:'id'});};r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});}
function store(name,mode='readonly'){return db.transaction(name,mode).objectStore(name)}
function getAll(name){return new Promise((res,rej)=>{const r=store(name).getAll();r.onsuccess=()=>res(r.result||[]);r.onerror=()=>rej(r.error);})}
function getOne(name,id){return new Promise((res,rej)=>{const r=store(name).get(id);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error);})}
function putOne(name,x){return new Promise((res,rej)=>{const r=store(name,'readwrite').put(x);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);})}
function delOne(name,id){return new Promise((res,rej)=>{const r=store(name,'readwrite').delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error);})}
const uid=()=>crypto.randomUUID?.()||String(Date.now()+Math.random());
const blank=(defs)=>Object.fromEntries(defs.map(([k])=>[k,'']));
const esc=(s='')=>String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
async function ensureCommon(){common=await getOne('commonSettings','global');if(!common){common={id:'global',sections:blank(commonSections),history:[],updatedAt:Date.now()};await putOne('commonSettings',common);}}
function hideEditors(){['emptyState','characterEditor','commonEditor','personaEditor'].forEach(id=>document.querySelector('#'+id).classList.add('hidden'));}
function show(id){hideEditors();document.querySelector('#'+id).classList.remove('hidden');}
function mark(m){dirty[m]=true;document.querySelector('#'+(m==='characters'?'charStatus':m==='common'?'commonStatus':'personaStatus')).textContent='未保存';}
function status(m,s){document.querySelector('#'+(m==='characters'?'charStatus':m==='common'?'commonStatus':'personaStatus')).textContent=s;}
function historyPush(obj,text){obj.history=obj.history||[];obj.history.push({at:new Date().toISOString(),text});}
function renderHistory(obj,id){const h=document.querySelector('#'+id);h.innerHTML='';(obj?.history||[]).slice().reverse().slice(0,50).forEach(x=>{const d=document.createElement('div');d.className='history-item';d.innerHTML=`<time>${new Date(x.at).toLocaleString('ja-JP')}</time>${esc(x.text)}`;h.appendChild(d);});}
function renderTabs(defs,active,boxId,onSelect){const box=document.querySelector('#'+boxId);box.innerHTML='';for(const [k,label] of defs){const b=document.createElement('button');b.textContent=label;b.className=active===k?'active':'';b.onclick=()=>onSelect(k);box.appendChild(b);}}
function renderTextPanel(obj,defs,key,panelId,onInput){const panel=document.querySelector('#'+panelId);panel.innerHTML='';const t=document.querySelector('#textSectionTemplate').content.cloneNode(true);const ta=t.querySelector('textarea');ta.value=obj?.sections?.[key]||'';ta.oninput=onInput;panel.appendChild(t);}
function fileToDataURL(file){return new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=()=>rej(r.error);r.readAsDataURL(file);});}
function captureChar(){if(!currentChar)return;const ta=document.querySelector('#charPanel .section-text');if(ta)currentChar.sections[charSection]=ta.value;currentChar.name=document.querySelector('#charName').value.trim();currentChar.subtitle=document.querySelector('#charSubtitle').value.trim();currentChar.tags=document.querySelector('#charTags').value.split(',').map(x=>x.trim()).filter(Boolean);}
function captureCommon(){const ta=document.querySelector('#commonPanel .section-text');if(ta)common.sections[commonSection]=ta.value;}
function capturePersona(){if(!currentPersona)return;const ta=document.querySelector('#personaPanel .section-text');if(ta)currentPersona.sections[personaSection]=ta.value;currentPersona.name=document.querySelector('#personaName').value.trim();currentPersona.subtitle=document.querySelector('#personaSubtitle').value.trim();currentPersona.tags=document.querySelector('#personaTags').value.split(',').map(x=>x.trim()).filter(Boolean);}
function captureCurrent(){if(mode==='characters')captureChar();else if(mode==='common')captureCommon();else capturePersona();}

function renderSide(){const f=document.querySelector('#searchInput').value.trim().toLowerCase();const box=document.querySelector('#sideList');box.innerHTML='';document.querySelector('#searchInput').style.display=mode==='common'?'none':'';document.querySelector('#newBtn').style.visibility=mode==='common'?'hidden':'visible';if(mode==='common'){const c=document.createElement('div');c.className='character-card active';c.innerHTML='<b>共通設定</b><span>世界・画像・人格境界</span>';c.onclick=()=>openCommon();box.appendChild(c);return;}const list=mode==='characters'?chars:personas;const cur=mode==='characters'?currentChar:currentPersona;list.filter(x=>!f||JSON.stringify(x).toLowerCase().includes(f)).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0)).forEach(x=>{const el=document.createElement('div');el.className='character-card'+(cur?.id===x.id?' active':'');el.innerHTML=`<b>${esc(x.name)}</b><span>${esc(x.subtitle||'')}</span>`;el.onclick=()=>mode==='characters'?openChar(x.id):openPersona(x.id);box.appendChild(el);});}
function setMode(m){captureCurrent();mode=m;document.querySelectorAll('#modeTabs button').forEach(b=>b.classList.toggle('active',b.dataset.mode===m));document.querySelector('#searchInput').value='';renderSide();if(m==='common')openCommon();else if(m==='characters'&&currentChar)openChar(currentChar.id);else if(m==='personas'&&currentPersona)openPersona(currentPersona.id);else show('emptyState');}
function renderGallery(){const g=document.querySelector('#gallery');g.innerHTML='';(currentChar?.images||[]).forEach((it,i)=>{const d=document.createElement('div');d.className='gallery-item';d.innerHTML=`<img src="${it.data}" alt=""><span class="badge">${esc(it.label||'画像')}</span><button>×</button>`;d.querySelector('button').onclick=()=>{currentChar.images.splice(i,1);historyPush(currentChar,'画像を削除');mark('characters');renderGallery();};g.appendChild(d);});}
function openChar(id){captureCurrent();currentChar=chars.find(c=>c.id===id);if(!currentChar)return;mode='characters';show('characterEditor');document.querySelector('#charName').value=currentChar.name||'';document.querySelector('#charSubtitle').value=currentChar.subtitle||'';document.querySelector('#charTags').value=(currentChar.tags||[]).join(', ');renderCharPanel();renderGallery();renderHistory(currentChar,'charHistory');dirty.characters=false;status('characters','保存済み');renderSide();}
function renderCharPanel(){renderTabs(charSections,charSection,'charTabs',k=>{captureChar();charSection=k;renderCharPanel();});renderTextPanel(currentChar,charSections,charSection,'charPanel',()=>mark('characters'));}
function openCommon(){captureCurrent();show('commonEditor');renderCommonPanel();renderHistory(common,'commonHistory');dirty.common=false;status('common','保存済み');renderSide();}
function renderCommonPanel(){renderTabs(commonSections,commonSection,'commonTabs',k=>{captureCommon();commonSection=k;renderCommonPanel();});renderTextPanel(common,commonSections,commonSection,'commonPanel',()=>mark('common'));}
function openPersona(id){captureCurrent();currentPersona=personas.find(p=>p.id===id);if(!currentPersona)return;mode='personas';show('personaEditor');document.querySelector('#personaName').value=currentPersona.name||'';document.querySelector('#personaSubtitle').value=currentPersona.subtitle||'';document.querySelector('#personaTags').value=(currentPersona.tags||[]).join(', ');renderPersonaPanel();renderHistory(currentPersona,'personaHistory');dirty.personas=false;status('personas','保存済み');renderSide();}
function renderPersonaPanel(){renderTabs(personaSections,personaSection,'personaTabs',k=>{capturePersona();personaSection=k;renderPersonaPanel();});renderTextPanel(currentPersona,personaSections,personaSection,'personaPanel',()=>mark('personas'));}

async function saveChar(){if(!currentChar)return;captureChar();currentChar.updatedAt=Date.now();historyPush(currentChar,'設定を保存');await putOne('characters',currentChar);chars=await getAll('characters');dirty.characters=false;status('characters','保存済み');renderSide();renderHistory(currentChar,'charHistory');}
async function saveCommon(){captureCommon();common.updatedAt=Date.now();historyPush(common,'共通設定を保存');await putOne('commonSettings',common);dirty.common=false;status('common','保存済み');renderHistory(common,'commonHistory');}
async function savePersona(){if(!currentPersona)return;capturePersona();currentPersona.updatedAt=Date.now();historyPush(currentPersona,'人格設定を保存');await putOne('personas',currentPersona);personas=await getAll('personas');dirty.personas=false;status('personas','保存済み');renderSide();renderHistory(currentPersona,'personaHistory');}
function compileSections(title,obj,defs){let out=`# ${title}\n`;for(const [k,label] of defs){const t=obj?.sections?.[k]?.trim();if(t)out+=`\n## ${label}\n${t}\n`;}return out.trim();}
function compileChar(c){let out=`# ${c.name}\n${c.subtitle?`\n${c.subtitle}\n`:''}`;if(c.tags?.length)out+=`\nタグ: ${c.tags.join(' / ')}\n`;for(const [k,label] of charSections){const t=c.sections?.[k]?.trim();if(t)out+=`\n## ${label}\n${t}\n`;}return out.trim();}
function compilePersona(p){let out=`# ${p.name}\n${p.subtitle?`\n${p.subtitle}\n`:''}`;if(p.tags?.length)out+=`\nタグ: ${p.tags.join(' / ')}\n`;for(const [k,label] of personaSections){const t=p.sections?.[k]?.trim();if(t)out+=`\n## ${label}\n${t}\n`;}return out.trim();}
async function compileFull(){captureCurrent();let out='# ママ図鑑：完全復元バックアップ\n\nこの文章は、新しいチャット／環境で人物・世界共通・人格運用をまとめて復元するための資料。後から明示的に修正・撤回された内容がある場合は、より新しい指示を優先する。\n';out+='\n\n# 共通設定\n'+compileSections('共通設定',common,commonSections);if(personas.length){out+='\n\n# 人格設定\n';for(const p of personas.sort((a,b)=>(a.name||'').localeCompare(b.name||'','ja')))out+='\n\n'+compilePersona(p);}if(chars.length){out+='\n\n# キャラクター設定\n';for(const c of chars.sort((a,b)=>(a.name||'').localeCompare(b.name||'','ja')))out+='\n\n'+compileChar(c);}return out;}

function stripFence(t=''){return t.trim().replace(/^```(?:json)?\s*/i,'').replace(/\s*```$/,'').trim();}
function normalizeCommon(x){if(!x)return null;if(Array.isArray(x))return x[0]||null;return x;}
function mergeSections(base,incoming,defs){base={...blank(defs),...(base||{})};if(incoming&&typeof incoming==='object')for(const [k,v] of Object.entries(incoming))if(defs.some(([key])=>key===k)&&typeof v==='string')base[k]=v;return base;}
function mergeRecord(existing,incoming,defs,kind){const now=Date.now();const base=existing||{id:incoming.id||uid(),name:incoming.name||'名称未設定',subtitle:'',tags:[],sections:blank(defs),history:[],updatedAt:now};if(incoming.name)base.name=incoming.name;if('subtitle'in incoming)base.subtitle=incoming.subtitle||'';if(Array.isArray(incoming.tags))base.tags=incoming.tags;base.sections=mergeSections(base.sections,incoming.sections,defs);if(kind==='character'&&Array.isArray(incoming.images))base.images=incoming.images;base.history=Array.isArray(base.history)?base.history:[];base.history.push({at:new Date().toISOString(),text:'設定貼り付けで更新'});base.updatedAt=now;return base;}
async function applyRaw(raw){let created=0,updated=0;const charIn=Array.isArray(raw)?raw:(raw.characters||((raw.kind==='character'||(!raw.kind&&raw.name))?[raw]:[]));const personaIn=raw.personas||(raw.kind==='persona'?[raw]:[]);const commonIn=normalizeCommon(raw.commonSettings||(raw.kind==='common'?raw:null));chars=await getAll('characters');personas=await getAll('personas');for(const inc of charIn||[]){if(!inc?.name)continue;const ex=(inc.id&&chars.find(x=>x.id===inc.id))||chars.find(x=>(x.name||'').trim()===(inc.name||'').trim());await putOne('characters',mergeRecord(ex,inc,charSections,'character'));ex?updated++:created++;}for(const inc of personaIn||[]){if(!inc?.name)continue;const ex=(inc.id&&personas.find(x=>x.id===inc.id))||personas.find(x=>(x.name||'').trim()===(inc.name||'').trim());await putOne('personas',mergeRecord(ex,inc,personaSections,'persona'));ex?updated++:created++;}if(commonIn){const inc=commonIn.sections?commonIn:{sections:commonIn};common.sections=mergeSections(common.sections,inc.sections,commonSections);historyPush(common,'設定貼り付けで更新');common.updatedAt=Date.now();await putOne('commonSettings',common);updated++;}chars=await getAll('characters');personas=await getAll('personas');common=await getOne('commonSettings','global');renderSide();return{created,updated};}
async function exportJSON(){if(dirty.characters)await saveChar();if(dirty.common)await saveCommon();if(dirty.personas)await savePersona();const data={version:3,exportedAt:new Date().toISOString(),characters:await getAll('characters'),commonSettings:await getOne('commonSettings','global'),personas:await getAll('personas')};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`mama-zukan-complete-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}

window.addEventListener('beforeunload',e=>{if(Object.values(dirty).some(Boolean)){e.preventDefault();e.returnValue='';}});
document.querySelectorAll('#modeTabs button').forEach(b=>b.onclick=()=>setMode(b.dataset.mode));
document.querySelector('#searchInput').oninput=renderSide;
['charName','charSubtitle','charTags'].forEach(id=>document.querySelector('#'+id).oninput=()=>mark('characters'));
['personaName','personaSubtitle','personaTags'].forEach(id=>document.querySelector('#'+id).oninput=()=>mark('personas'));
document.querySelector('#saveCharBtn').onclick=saveChar;document.querySelector('#saveCommonBtn').onclick=saveCommon;document.querySelector('#savePersonaBtn').onclick=savePersona;
document.querySelector('#copyCharBtn').onclick=async()=>{captureChar();await navigator.clipboard.writeText(compileChar(currentChar));status('characters','コピーしました');};
document.querySelector('#copyCommonBtn').onclick=async()=>{captureCommon();await navigator.clipboard.writeText(compileSections('共通設定',common,commonSections));status('common','コピーしました');};
document.querySelector('#copyPersonaBtn').onclick=async()=>{capturePersona();await navigator.clipboard.writeText(compilePersona(currentPersona));status('personas','コピーしました');};
document.querySelector('#copyFullBtn').onclick=async()=>{await navigator.clipboard.writeText(await compileFull());alert('キャラ＋共通設定＋人格設定をまとめた完全復元文をコピーしました');};
document.querySelector('#deleteCharBtn').onclick=async()=>{if(!currentChar||!confirm(`${currentChar.name} を削除しますか？`))return;await delOne('characters',currentChar.id);currentChar=null;chars=await getAll('characters');show('emptyState');renderSide();};
document.querySelector('#deletePersonaBtn').onclick=async()=>{if(!currentPersona||!confirm(`${currentPersona.name} を削除しますか？`))return;await delOne('personas',currentPersona.id);currentPersona=null;personas=await getAll('personas');show('emptyState');renderSide();};
document.querySelector('#clearCharHistory').onclick=()=>{currentChar.history=[{at:new Date().toISOString(),text:'履歴を整理'}];mark('characters');renderHistory(currentChar,'charHistory');};
document.querySelector('#clearCommonHistory').onclick=()=>{common.history=[{at:new Date().toISOString(),text:'履歴を整理'}];mark('common');renderHistory(common,'commonHistory');};
document.querySelector('#clearPersonaHistory').onclick=()=>{currentPersona.history=[{at:new Date().toISOString(),text:'履歴を整理'}];mark('personas');renderHistory(currentPersona,'personaHistory');};
document.querySelector('#imageInput').onchange=async e=>{if(!currentChar)return;currentChar.images=currentChar.images||[];for(const f of e.target.files)currentChar.images.push({id:uid(),label:f.name,data:await fileToDataURL(f)});historyPush(currentChar,`${e.target.files.length}枚の画像を追加`);mark('characters');renderGallery();e.target.value='';};
document.querySelector('#newBtn').onclick=()=>{document.querySelector('#newDialogTitle').textContent=mode==='personas'?'新しい人格':'新しい人物';document.querySelector('#newDialog').showModal();};
document.querySelector('#newForm').addEventListener('submit',async()=>{const name=document.querySelector('#newName').value.trim();if(!name)return;const c={id:uid(),name,subtitle:document.querySelector('#newSubtitle').value.trim(),tags:[],sections:blank(mode==='personas'?personaSections:charSections),history:[{at:new Date().toISOString(),text:'新規作成'}],updatedAt:Date.now()};if(mode==='characters'){c.images=[];await putOne('characters',c);chars=await getAll('characters');setTimeout(()=>openChar(c.id));}else{await putOne('personas',c);personas=await getAll('personas');setTimeout(()=>openPersona(c.id));}document.querySelector('#newName').value='';document.querySelector('#newSubtitle').value='';});
document.querySelector('#exportBtn').onclick=exportJSON;
document.querySelector('#importInput').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const raw=JSON.parse(await f.text());if(!confirm('バックアップを読み込みます。同じID／名前の項目は更新されます。続けますか？'))return;await applyRaw(raw);alert('読み込み完了');}catch(err){alert('読み込みに失敗しました: '+err.message)}finally{e.target.value='';}};
document.querySelector('#pasteImportBtn').onclick=()=>{document.querySelector('#pasteInput').value='';document.querySelector('#pasteDialog').showModal();};document.querySelector('#clearPasteBtn').onclick=()=>document.querySelector('#pasteInput').value='';
document.querySelector('#copySchemaBtn').onclick=async()=>{const schema={version:3,characters:[{name:'人物名',subtitle:'立場・呼称',tags:[],sections:Object.fromEntries(charSections.map(([k,l])=>[k,l]))}],commonSettings:{sections:Object.fromEntries(commonSections.map(([k,l])=>[k,l]))},personas:[{name:'人格名',subtitle:'役割',tags:[],sections:Object.fromEntries(personaSections.map(([k,l])=>[k,l]))}]};await navigator.clipboard.writeText(JSON.stringify(schema,null,2));alert('完全復元用のJSON形式をコピーしました');};
document.querySelector('#pasteApplyBtn').onclick=async()=>{const t=document.querySelector('#pasteInput').value.trim();if(!t){alert('JSONを貼り付けてください');return;}try{const r=await applyRaw(JSON.parse(stripFence(t)));document.querySelector('#pasteDialog').close();alert(`読み込み完了：新規 ${r.created} / 更新 ${r.updated}`);}catch(err){alert('読み込みに失敗しました: '+err.message)}};
(async()=>{db=await openDB();await ensureCommon();chars=await getAll('characters');personas=await getAll('personas');renderSide();if('serviceWorker'in navigator&&location.protocol!=='file:')navigator.serviceWorker.register('./sw.js').catch(()=>{});})();
